#!/usr/bin/env python3
"""Generate GLOSSARY.<lang>.md tables from glossary.json (the canonical source).

English (en) is primary: it is the key and the reference. Other languages are
translations and may lag — a missing translation falls back to the English term
with a `⚠ (en)` marker so gaps are visible.

Usage:
    python3 gen.py            # regenerate GLOSSARY.en.md / .es.md / .fr.md
    python3 gen.py --check    # exit 1 if any generated file is stale (CI guard)

Tool-agnostic: stdlib only, no dependencies.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "glossary.json")

HEADINGS = {
    "en": {
        "title": "Glossary — Forest vocabulary (EN)",
        "intro": "Canonical multilingual vocabulary of the `.roots` / Forest model. "
                 "Generated from `glossary.json` — do not edit by hand; run `gen.py`.",
        "primary": "English is the primary language (the key). Spanish/French are translations.",
        "term": "Term", "definition": "Definition", "see": "See also", "missing": "⚠ translation missing",
    },
    "es": {
        "title": "Glosario — vocabulario Forest (ES)",
        "intro": "Vocabulario multilingüe canónico del modelo `.roots` / Forest. "
                 "Generado desde `glossary.json` — no editar a mano; correr `gen.py`.",
        "primary": "El inglés es el idioma principal (la key). Español/francés son traducciones.",
        "term": "Término", "definition": "Definición", "see": "Ver también", "missing": "⚠ falta traducción",
    },
    "fr": {
        "title": "Glossaire — vocabulaire Forest (FR)",
        "intro": "Vocabulaire multilingue canonique du modèle `.roots` / Forest. "
                 "Généré depuis `glossary.json` — ne pas éditer à la main ; lancer `gen.py`.",
        "primary": "L'anglais est la langue principale (la clé). Espagnol/français sont des traductions.",
        "term": "Terme", "definition": "Définition", "see": "Voir aussi", "missing": "⚠ traduction manquante",
    },
}


def load():
    with open(SRC, encoding="utf-8") as fh:
        return json.load(fh)


def pick(entry, lang):
    """Return (term, definition, is_fallback) for a term entry in a language."""
    block = entry.get(lang)
    if block and block.get("term"):
        return block["term"], block.get("def", ""), False
    en = entry.get("en", {})
    return en.get("term", ""), en.get("def", ""), True


def render(data, lang):
    h = HEADINGS[lang]
    cats = data.get("categories", {})
    terms = data["terms"]
    # group term keys by category, preserving JSON order within each group
    by_cat = {}
    for key, entry in terms.items():
        by_cat.setdefault(entry.get("category", "other"), []).append((key, entry))

    out = []
    out.append(f"<!-- GENERATED by gen.py from glossary.json — DO NOT EDIT BY HAND -->")
    out.append(f"# {h['title']}")
    out.append("")
    out.append(f"> {h['intro']}")
    out.append(f">")
    out.append(f"> {h['primary']}")
    out.append("")

    # category order follows the order declared in `categories`
    cat_order = list(cats.keys()) + [c for c in by_cat if c not in cats]
    for cat in cat_order:
        if cat not in by_cat:
            continue
        cat_label = cats.get(cat, {}).get(lang) or cats.get(cat, {}).get("en") or cat
        out.append(f"## {cat_label}")
        out.append("")
        out.append(f"| {h['term']} | {h['definition']} | {h['see']} |")
        out.append("|---|---|---|")
        for key, entry in by_cat[cat]:
            term, definition, fallback = pick(entry, lang)
            if fallback and lang != "en":
                term = f"{term} _({h['missing']})_"
            see = entry.get("see_also", [])
            see_terms = []
            for ref in see:
                ref_entry = terms.get(ref)
                if ref_entry:
                    rt, _, _ = pick(ref_entry, lang)
                    see_terms.append(rt)
            see_cell = " · ".join(see_terms)
            # escape pipes inside cells
            definition = definition.replace("|", "\\|")
            out.append(f"| **{term}** | {definition} | {see_cell} |")
        out.append("")

    out.append("---")
    out.append(f"<!-- {len(terms)} terms · primary_lang={data['meta']['primary_lang']} "
               f"· languages={','.join(data['meta']['languages'])} -->")
    out.append("")
    return "\n".join(out)


def main():
    check = "--check" in sys.argv
    data = load()
    stale = []
    for lang in data["meta"]["languages"]:
        path = os.path.join(HERE, f"GLOSSARY.{lang}.md")
        content = render(data, lang)
        if check:
            existing = open(path, encoding="utf-8").read() if os.path.exists(path) else None
            if existing != content:
                stale.append(os.path.basename(path))
        else:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
            print(f"wrote {os.path.basename(path)} ({len(data['terms'])} terms)")
    if check and stale:
        print("STALE (run gen.py): " + ", ".join(stale), file=sys.stderr)
        sys.exit(1)
    if check:
        print("glossary tables up to date")


if __name__ == "__main__":
    main()
